### ISSUE TITLE
Tagged version contains the typo in your bower.json file

### ISSUE THREAD

**Issue by majoncas** [jgarber623/javascript-debounce#2]
Could you create a tag with the typo corrected in your bower.json file please? By default, bower loads the first tag he can found which leads to your 1.0.0 tagged version containing the wrong name.

**Comment by jgarber623** [comment]
Thanks, @majoncas! Good catch and apologies for the trouble.

**Comment by majoncas** [comment]
No worries, thank you for your quick response :) !!!
